function M = get_M(W, A, sample, miu) 
nv = size(W, 1);
I = spdiags(ones(nv,1),0,nv,nv);
B = I(sample, :);
%     Opr = LBO; %for gradient 
% Opr = LBO'*LBO; %for laplacian
% Opr = A\W; %for gradient 
Opr = W'/(A^2)*W;%for laplacian
M1 = (Opr + miu * (B'*B));
M2 = miu*B';
M = M1\M2;
% [Ql, D, Qr] = svd(full(M1));
% d = diag(D);
% d_ = 1./d;
% D_ = zeros(size(D'));
% N = min(size(D, 1), size(D, 2));
% D_(1:N, 1:N) = diag(d_(1:N));    
% M1_ = Qr*D_*Ql';
% M_svd = M1_*M2;
